### PR TITLE
Use OS-dependent path separator

### PR DESCRIPTION
**Pull request by sormuras**
Fix
```
error: illegal argument for --module-source-path: cannot set path for module se.jbee.inject
javadoc: error - module se.jbee.inject not found.
```

### CODE REVIEW

**Comment by sormuras** [comment]
Wait a second before merging this time. ;-)

**Comment by jbee** [comment]
I think I was getting this locally with JDK11

**Comment by jbee** [comment]
I mean I was getting a similar error even before your javadoc changes. There might be another similar issue somewhere.

**Comment by sormuras** [comment]
Yes, JDK 11 doesn't support the module-specific form of `--module-source-path`. It was introduced in JDK 12. See https://bugs.openjdk.java.net/browse/JDK-8208609 for details.

https://github.com/jbee/silk/pull/85/checks?check_run_id=733516568#step:5:688

Good to merge. ✔

**Comment by sormuras** [comment]
> Yes, JDK 11 doesn't support the module-specific form of --module-source-path. It was introduced in JDK 12. See https://bugs.openjdk.java.net/browse/JDK-8208609 for details.

If Silk was organizing its sources in folders that contain module names, it would allow JDK 11 to be used and most of the custom "realm building code" in `Build.java` could be removed.

**Comment by jbee** [comment]
> If Silk was organizing its sources in folders that contain module names, it would allow JDK 11 to be used and most of the custom "realm building code" in Build.java could be removed.

Then we should do that :D - Maybe get rid of ant first so we don't have to do extra work that later has no value.

**Pull request merged**
