### PR TITLE
Introduce Bach.java as build tool

### PR DESCRIPTION
**Pull request by sormuras**
## Overview

This draft PR introduces [Bach.java](https://github.com/sormuras/bach#features) as a potential new build tool for Silk DI.

### Deliverables

- [x] Introduce module descriptor `se.jbee.inject` with all bells and whistles.
- [x] Core realm, including module `se.jbee.inject`, is compiled to Java SE release 8.
- [x] Integrate in CI system via GitHub Actions
- [x] Test realm with all unit and integration tests being green.
- [ ] Create modular API documentation (`javadoc` 14 reports a bunch of warnings and errors).

### Build

- Install JDK 14
- Call `jshell https://sormuras.de/bach-build`

## Project Descriptor

The following printout of Silk's project descriptor is the current result of the configuration process encoded in `Build.java`, the custom build program. It will change over time, till the PR is ready for review. Find the latest-and-greatest printout in the `.bach/workspace/summary.md` file.

> If Silk used a more JDK-like directory tree pattern below `src/`, Bach could scan that automatically.

```text
Project
	title: Silk DI
	version: 1-ea
	realms: [core] << 1 distinct unit(s)
	declares: [se.jbee.inject]
	requires: [java.desktop, java.logging, java.management]
	external: []
	Realm core
		flags: []
		upstreams: []
		Unit se.jbee.inject
			Module Descriptor se.jbee.inject
				main-class: -
				requires: [java.base, java.desktop, java.logging, java.management]
			Sources
				path: src/core
				release: 8
				path: src/core-module
				release: 9
```

### CODE REVIEW

**Comment by sormuras** [comment]
Preliminary marked as ready for review to let GitHub Actions kick in...

**Comment by sormuras** [comment]
...which didn't happen. Converting PR back to draft.

**Comment by sormuras** [comment]
A draft PR targeted at my cloned repository triggered the workflows: https://github.com/sormuras/silk/pull/2/checks

Ant and Bach are working over there:

image

**Comment by sormuras** [comment]
Tests are on their way...

```
Test run finished after 925 ms
[        93 containers found      ]
[         0 containers skipped    ]
[        93 containers started    ]
[         0 containers aborted    ]
[        93 containers successful ]
[         0 containers failed     ]
[       377 tests found           ]
[         0 tests skipped         ]
[       377 tests started         ]
[         0 tests aborted         ]
[       373 tests successful      ]
[         4 tests failed          ]
```

...with only 4 failed. Find them with stacktrace snippets below:

```
  JUnit Vintage:TestAggregatingEvents:dynamicAggregationIsPerformed
    MethodSource [className = 'se.jbee.inject.event.TestAggregatingEvents', methodName = 'dynamicAggregationIsPerformed', methodParameterTypes = '']
    => java.lang.NullPointerException
       se.jbee.inject/se.jbee.inject.event.$Proxy29.dynamic(Unknown Source)
       se.jbee.inject/se.jbee.inject.event.TestAggregatingEvents.dynamicAggregationIsPerformed(TestAggregatingEvents.java:101)
```

```
  JUnit Vintage:TestAggregatingEvents:staticAggregationIsPerformed
    MethodSource [className = 'se.jbee.inject.event.TestAggregatingEvents', methodName = 'staticAggregationIsPerformed', methodParameterTypes = '']
    => java.lang.NullPointerException
       se.jbee.inject/se.jbee.inject.event.$Proxy29.all(Unknown Source)
       se.jbee.inject/se.jbee.inject.event.TestAggregatingEvents.staticAggregationIsPerformed(TestAggregatingEvents.java:95)
```

```
  JUnit Vintage:TestRoundRobinComputeEvents:computationUsesAllAvailableServices
    MethodSource [className = 'se.jbee.inject.event.TestRoundRobinComputeEvents', methodName = 'computationUsesAllAvailableServices', methodParameterTypes = '']
    => se.jbee.inject.event.EventException
       se.jbee.inject/se.jbee.inject.event.ConcurrentEventProcessor.doCompute(ConcurrentEventProcessor.java:219)
       se.jbee.inject/se.jbee.inject.event.ConcurrentEventProcessor.doProcess(ConcurrentEventProcessor.java:212)
       se.jbee.inject/se.jbee.inject.event.ConcurrentEventProcessor.lambda$compute$5(ConcurrentEventProcessor.java:200)
```

```
  JUnit Vintage:TestServiceLoaderBootstrapBinds:serviceLoaderCanBeUsedToDeclareModuleRoots
    MethodSource [className = 'se.jbee.inject.bind.TestServiceLoaderBootstrapBinds', methodName = 'serviceLoaderCanBeUsedToDeclareModuleRoots', methodParameterTypes = '']
    => No matching resource found.
	 dependency: java.lang.Integer *
	available are (for same raw type): none
	
       se.jbee.inject/se.jbee.inject.container.Container$InjectorImpl.noResourceFor(Container.java:294)
       se.jbee.inject/se.jbee.inject.container.Container$InjectorImpl.resolveFromUpperBound(Container.java:277)
       se.jbee.inject/se.jbee.inject.container.Container$InjectorImpl.resolve(Container.java:262)
       se.jbee.inject/se.jbee.inject.Injector.resolve(Injector.java:59)
       se.jbee.inject/se.jbee.inject.bind.TestServiceLoaderBootstrapBinds.serviceLoaderCanBeUsedToDeclareModuleRoots(TestServiceLoaderBootstrapBinds.java:41)
```

Guess, some of them require the "example" project to be available on the class path. Working that out tonight. Or will ignore them for the time being... 😱

**Comment by jbee** [comment]
> will ignore them for the time being

That is fine. Does not look to be critical or hard to fix later ones. 

BTW if you need me to do something or have a closer look please ping me and make that explicit. Currently not much online and might miss that otherwise.

**Comment by sormuras** [comment]
"Fixed" one or two by keeping them close to the example module. The other tests are ignored.

Yeah, please take a look at this screenshot attached to sormuras/silk#2 -- maybe you can spot the code setting the `null` at first glance.

**Comment by sormuras** [comment]
Wohoo! 🎶

**Pull request merged**
