### PR TITLE
Bumped Java source and target to 1.8 in Ant

### PR DESCRIPTION
**Pull request by jest**

### CODE REVIEW

**Comment by jbee** [comment]
thanks @jest

**Comment by jest** [comment]
Thanks. @jbee On the wider angle: are you interested in more contribution? Mainly in the build process, as I'm not that much into Silk yet, just evaluating as a potential lighter alternative to Guava in our product (hence the build improvements)? Are there any chances for discussion with users, other than issues and PRs?

**Comment by jbee** [comment]
Improvements are always welcome.
That said, I would not consider e.g. maven an improvement over ant. However, if you want to add support for such a build tool this is fine with me. As silk has no dependencies the build should be simple no matter what tool. 

In the future silk can be divided into 3-4 useful java modules. The packages are already organised so that dependencies are only one way.

I have no idea who is using silk. All I can say, is that I never had anyone complain. For what I know it just works. Feel free to ask me any questions.

When it comes to user experience my opinion is surely biased, still, I used guava for years and that experience was so awful that I build silk. That should maybe tell you something ;)

Short aside: spring or dagger are even more insane for that matter.

Like so many frameworks they appeal especially to those who have not used them yet.
When you do you soon discover a different side. A lot of time is spend googling and working around problems that should not have existed in the first place. If you are lucky you can write and maintain a awful lot of fragile code to do common things. Often you just can't and it simply won't work. Instead you start rethinking your app to fit the framework better. At this point people should understand that something is very wrong and stop. For some reason most don't. 3 years later they need 10x the stuff to maintain a "network of interconnected problems" a.k.a. a mess. 

Most problems arise from the unwise idea of annotation based dependency injection that turns the natural direction of code dependencies upside down. It takes some thought but than it should be obvious how bad this idea is. So silk was designed to not going down that road. Using code to describe the dependencies makes things as simple as they are. It needs no special tool support to be "refactoring safe". No magic semantics have to be learned that break in some special cases. Instead it is just usual code. Everyone can debug it - should it be needed.

But projects end up with spring, guava and co anyway. Because they are "approved standards" and "enterprise". Somehow developers seamed to refuse the concept of pop culture: A lot of people showing the same bad taste for social reasons. As if a big company behind a bad idea makes the problems you will face magically go away. What can I say, in my experience it never goes that way.

**Comment by jest** [comment]
Saying Guava I meant Guice :)

The reasons you mention are also things pushing me a bit away from compile-time solutions, like Dagger or Spring DI. I need dependency injection for constructing a run-time (request-based, so: unpredictable), configuration-based search algoritms for combinatorial optimization. So any solution using annotations and/or code generation is inferior to API-based.

Guice API is not bad. Errors reporting is really good. But I have a lot of headaches, where injections should be scoped to a given child injector/private module, with no "leaks" to parent, or errors when there is already a parent injector binding for the same key. From what I see, Named from Silk would be a good fit here, as it participates in resolution process with "longest prefix" winning over shorter ones.

As for the entrprise tools API. I still wonder how all around me use Spring for everything (not even understanding it fully), or wonder on how beautiful world will be with Jigsaw, but raise eyebrows when I mention using OSGi for years and asking for proper support in IDE other than Eclipse... Now Kotlin becomes "a thing", but when I ask for better support in Eclipse, I'm told to "just use IntelliJ"...

**Comment by jbee** [comment]
I read and meant that as guava + guice ;)

Runtime... Do you construct most of your instances per request? So the container becomes more of a "factory"? Or do you mean that you construct a tree of dependent objects whose job it is to process requests including some objects being request scoped (created per request)?

Guice API was an important step in the right direction. Still the model underneath is one made for using annotations, meaning: assembly is upside down. Private modules are more of a hack to partly get around this flaw. As you discovered they just lead to even more complicated problems until one cannot solve them by definition.
 
Guice has made an effort to produce useful error messages - if compared with spring.  
But I rather get rid of all the strange corner cases than trying to explain to the user why this even is considered an error or why you cannot do it this way or that. 
Silk is simple. If modules conflict it tells you what bindings cause the problem. If you get past that phase you are fine.

As you say parent/child relations are very easy to solve in silk using names. Also there is `injectingInto` and `within` to scope the binding to just a particular (set of) parent(s). In general silk is build so that bindings can be precisely applied to the set of instances in the graph that should be targeted in the way programmers usually think about their program graphs. 
The bindings are true sets, meaning they can be made in any module and multiple times as long as they do not conflict. 

Yes... I know. Most projects I get so work with don't even work in eclipse any longer. IntelliJ "solves" this by skipping the whole "direct feedback" - you have to manage compilation yourself and find errors at build or runtime - what an "improvement".

**Pull request merged**
